### random sub module

#### rand 함수

 - 0, 1 사이의 분포로 랜덤한 ndarray 생성


In [0]:
np.random.rand(2, 2)

array([[0.43972715, 0.46104541],
       [0.47389371, 0.24581654]])

#### randn 함수 
 - n: normal distribution(정규분포)
 - 정규분포로 샘플링 된 랜덤 ndarray 생성

In [0]:
np.random.randn(2, 2)

array([[ 0.02481912,  0.64814712],
       [-0.52125724,  1.81512797]])

#### randint 함수

 - 특정 정수 사이에서 랜덤하게 샘플링

In [0]:
np.random.randint(2, 100, (6, 3))

array([[30, 86, 59],
       [53, 71, 46],
       [45, 69, 18],
       [77, 21, 47],
       [ 3, 83, 90],
       [68, 74, 38]])

#### seed 함수

 - 랜덤한 값을 동일하게 다시 생성하고자 할 때 사용

In [0]:
np.random.seed(100)

In [0]:
np.random.randn(3, 4)

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349]])

#### choice
 - 주어진 1차원 ndarray로부터 랜덤으로 샘플링
 - 정수가 주어진 경우 np.arange(해당숫자)로 간주

In [0]:
np.random.choice(100, (3, 4))

array([[ 4, 91, 59, 67],
       [ 7, 49, 47, 65],
       [61, 14, 55, 71]])

In [0]:
x = np.array([1, 2, 3, 1.5, 2.6, 4.9])
np.random.choice(x, (2, 2))

array([[2.6, 3. ],
       [2.6, 1.5]])

#### 확률분포에 따른 ndarray 생성

 - uniform
 - normal 등

In [0]:
np.random.uniform(1.0, 3.0, (4, 5))

array([[2.8020262 , 2.58975752, 2.62292196, 2.28055611, 2.24955902],
       [1.29101502, 2.1404318 , 1.130225  , 1.62682514, 1.43413153],
       [2.05390078, 1.85421676, 2.96526085, 1.28090297, 2.49682321],
       [2.57768079, 2.46079323, 2.69123668, 2.11238076, 1.11372542]])

In [0]:
np.random.normal(1.0, 3.0, (4, 5))

array([[-0.678459  ,  1.16860285,  0.67635237,  1.26692185, -0.24754094],
       [ 6.65200438, -4.63104178, -1.59851756,  5.57554056,  2.16248039],
       [ 0.84171374,  1.33739261, -1.66024523, -1.50114816,  6.99079357],
       [ 3.03766271,  3.87897143,  0.92062907,  6.42864864,  2.79731423]])

### indexing 

 - python list 와 동일한 개념으로 사용
 - , 를 사용하여 각 차원의 인덱스에 접근가능
 
 #### 1차원 벡터 인덱싱

In [0]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
x[0]

1

In [0]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

#### 2차원 행렬 인덱싱

In [0]:
x = np.arange(10).reshape(2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [0]:
x[0, 3]

3

#### 3차원 텐서 인덱싱

In [0]:
x = np.arange(36).reshape(3, 4, 3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [0]:
x[1, 3, 2]

23