#### 연산함수

 - add,substract, multiply, divide

In [0]:
np.add(x, y)

array([[ 0.07476922,  1.56237941,  2.18774368,  3.57311471,  4.13546506],
       [ 5.37562767,  6.33001114,  7.547794  ,  8.19797026,  9.25155065],
       [10.80938403, 11.92580965, 12.89988772, 13.43454589, 14.02134634]])

In [0]:
np.subtract(x, y)

array([[-0.07476922,  0.43762059,  1.81225632,  2.42688529,  3.86453494],
       [ 4.62437233,  5.66998886,  6.452206  ,  7.80202974,  8.74844935],
       [ 9.19061597, 10.07419035, 11.10011228, 12.56545411, 13.97865366]])

In [0]:
np.multiply(x, y)

array([[ 0.        ,  0.56237941,  0.37548735,  1.71934412,  0.54186022],
       [ 1.87813835,  1.98006685,  3.83455803,  1.5837621 ,  2.26395588],
       [ 8.09384029, 10.1839062 , 10.79865259,  5.64909651,  0.29884872]])

In [0]:
np.divide(x, y)

array([[  0.        ,   1.778159  ,  10.65282216,   5.2345542 ,
         29.52791027],
       [ 13.31105346,  18.18120434,  12.77852612,  40.41010949,
         35.77808239],
       [ 12.35507453,  11.88149199,  13.33499701,  29.91628834,
        655.85022743]])

In [0]:
x+y

array([[ 0.07476922,  1.56237941,  2.18774368,  3.57311471,  4.13546506],
       [ 5.37562767,  6.33001114,  7.547794  ,  8.19797026,  9.25155065],
       [10.80938403, 11.92580965, 12.89988772, 13.43454589, 14.02134634]])

In [0]:
x-y

array([[-0.07476922,  0.43762059,  1.81225632,  2.42688529,  3.86453494],
       [ 4.62437233,  5.66998886,  6.452206  ,  7.80202974,  8.74844935],
       [ 9.19061597, 10.07419035, 11.10011228, 12.56545411, 13.97865366]])

In [0]:
x*y

array([[ 0.        ,  0.56237941,  0.37548735,  1.71934412,  0.54186022],
       [ 1.87813835,  1.98006685,  3.83455803,  1.5837621 ,  2.26395588],
       [ 8.09384029, 10.1839062 , 10.79865259,  5.64909651,  0.29884872]])

In [0]:
x/y

array([[  0.        ,   1.778159  ,  10.65282216,   5.2345542 ,
         29.52791027],
       [ 13.31105346,  18.18120434,  12.77852612,  40.41010949,
         35.77808239],
       [ 12.35507453,  11.88149199,  13.33499701,  29.91628834,
        655.85022743]])

#### 통계함수

 - 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장


In [0]:
print(y)

[[0.07476922 0.56237941 0.18774368 0.57311471 0.13546506]
 [0.37562767 0.33001114 0.547794   0.19797026 0.25155065]
 [0.80938403 0.92580965 0.89988772 0.43454589 0.02134634]]


In [0]:
y.mean()

0.42182662770270496

In [0]:
np.mean(y)

0.42182662770270496

In [0]:
y.max()

0.9258096547208036

In [0]:
y.min()

0.0213463370361493

In [0]:
np.argmax(y)

11

In [0]:
np.var(y)

0.07991439039961593

In [0]:
np.median(y)

0.37562767036630995

In [0]:
np.std(y)

0.28269133414311787

#### 집계함수

 - 합계(sum), 누적합계(cumsum) 등등 계산 가능

In [0]:
y

array([[0.07476922, 0.56237941, 0.18774368, 0.57311471, 0.13546506],
       [0.37562767, 0.33001114, 0.547794  , 0.19797026, 0.25155065],
       [0.80938403, 0.92580965, 0.89988772, 0.43454589, 0.02134634]])

In [0]:
np.sum(y)

6.327399415540574

In [0]:
np.cumsum(y)

array([0.07476922, 0.63714862, 0.8248923 , 1.39800701, 1.53347206,
       1.90909973, 2.23911087, 2.78690488, 2.98487514, 3.23642579,
       4.04580982, 4.97161948, 5.87150719, 6.30605308, 6.32739942])

In [0]:
np.sum(y, axis=0)

array([1.25978091, 1.8182002 , 1.6354254 , 1.20563086, 0.40836205])

In [0]:
np.sum(y, axis=1)

array([1.53347206, 1.70295373, 3.09097362])

#### any, all 함수

 - any : 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all : 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [0]:
z = np.random.randn(10)
z

array([ 0.37366107, -0.59261061,  0.53227718, -1.87069861,  0.99547727,
        0.1974419 ,  1.58175446, -1.15943105, -1.77634093, -0.46029691])

In [0]:
np.any(z > 0)

True

In [0]:
np.all(z != 0)

True

In [0]:
z > 0

array([ True, False,  True, False,  True,  True,  True, False, False,
       False])

#### where 함수

 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인 경우는 0, 나머지는 그대로 값을 쓰는 경우

In [0]:
z = np.random.randn(10)
z

array([ 0.93899497, -0.84156929, -0.38708048,  1.06202531, -0.07978209,
        1.24851367,  0.82146664,  0.47029365,  0.53776201,  0.52638025])

In [0]:
np.where(z > 0, z, 0)  # 조건, True, False

array([0.93899497, 0.        , 0.        , 1.06202531, 0.        ,
       1.24851367, 0.82146664, 0.47029365, 0.53776201, 0.52638025])