#### 슬라이싱

 - 리스트, 문자열 slicing과 동일한 개념으로 사용
 - ,를 사용하여 각 차원 별로 슬라이싱 가능
 
#### 1차원 벡터 슬라이싱

In [0]:
x = np.arange(10)

In [0]:
x[1:7]

array([1, 2, 3, 4, 5, 6])

#### 2차원 행렬 슬라이싱

In [0]:
x = np.arange(10).reshape(2, 5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [0]:
x[1, 1:3]

array([6, 7])

#### 3차원 텐서 슬라이싱

In [0]:
x = np.arange(36).reshape(3, 4, 3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [0]:
x[:2, :3, :2]

array([[[ 0,  1],
        [ 3,  4],
        [ 6,  7]],

       [[12, 13],
        [15, 16],
        [18, 19]]])

#### ravel, np.ravel

 - 다차원배열을 1차원으로 변경
 - 'order'파라미터
     - 'C' - row 우선변경
     - 'F' - column 우선변경

In [0]:
x = np.arange(15).reshape(3, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [0]:
x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [0]:
np.ravel(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [0]:
temp = x.ravel()
temp

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [0]:
temp[0] = 100
print(temp)
print(x)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]


#### flatten

 - 다차원 배열을 1차원으로 변경
 - ravel 과의 차이점 : copy를 생성하여 변경함(즉, 원본데이터가 아닌 복사본을 반환)
 - 'order' 파라미터
     - 'C' - row 우선변경
     - 'F' - column 우선 변경

In [0]:
y = np.arange(15).reshape(3, 5)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [0]:
y.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [0]:
y.flatten(order='F')

array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

In [0]:
temp = y.flatten()

In [0]:
temp[0] = 100
print(temp)
print(y)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


#### reshape 함수

 - array의 shape을 다른 차원으로 변경
 - 주의할 점은 reshape한 후의 결과의 전체 원소 개수와 이전 개수가 같아야 가능
 - 사용 
     * 예) 이미지 데이터 벡터화 - 이미지는 기본적으로 2차원 혹은 3차원(RGB)이나 트레이닝을 위해 1차원으로 변경하여 사용 됨

In [0]:
x = np.arange(36)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [0]:
x.shape

(36,)

In [0]:
x.ndim

1

In [0]:
x.reshape(6, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [0]:
x.reshape(6, -1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [0]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.07476922 0.56237941 0.18774368 0.57311471 0.13546506]
 [0.37562767 0.33001114 0.547794   0.19797026 0.25155065]
 [0.80938403 0.92580965 0.89988772 0.43454589 0.02134634]]
