#### 다중 조건 사용하기

 - 파이썬 논리 연산자인 and, or, not 키워드 사용 불가
 - & : and
 - | : or
 

In [0]:
x[(x % 2 == 0) & (x < 30)]

array([20, 28, 22,  2])

In [0]:
x[(x > 50) | (x < 30)]

array([89, 20, 28, 22,  1, 74,  2, 52, 97, 87, 27])

#### 예제 ) 2019년 7월 서울 평균기온 데이터

 - 평균기온이 25도를 넘는 날수는?
 - 평균기온이 25를 넘는 날의 평균 기온은?

In [0]:
temp = np.array([23.9, 24.4, 24.1, 25.4, 27.6, 29.7, 26.7, 25.1,
                 25.0, 22.7, 21.9, 23.6, 24.9, 25.9, 23.8, 24.7,
                 25.6, 26.9, 28.6, 28.0, 25.1, 26.7, 28.1, 26.5,
                 26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [0]:
len(temp)

31

In [0]:
jul = temp[temp > 25.0]
len(jul)

21

In [0]:
round(np.mean(jul), 2)

26.86

#### broadcasting 

 - Shape이 같은 두 ndarray에 대한 연산은 각 원소별로 진행
 - 연산되는 두 ndarray가 다른 shape 을 갖는 경우 broadcasting (shape을 맞춤) 후 진행

In [0]:
x = np.arange(15).reshape(3, 5)
y = np.random.randn(15).reshape(3, 5)

In [0]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [0]:
y

array([[-1.72846517,  0.1279487 ,  0.24103492, -0.45318273, -0.5521511 ],
       [-1.18167988,  0.39164413,  0.28541158, -0.81640977, -0.46050693],
       [ 0.38389859,  0.22183107, -0.61463231, -0.03690989,  0.15397131]])

In [0]:
x+y

array([[-1.72846517,  1.1279487 ,  2.24103492,  2.54681727,  3.4478489 ],
       [ 3.81832012,  6.39164413,  7.28541158,  7.18359023,  8.53949307],
       [10.38389859, 11.22183107, 11.38536769, 12.96309011, 14.15397131]])

#### scalar(상수)와의 연산

In [0]:
x * 2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

#### shape이 다른 경우 연산 

In [0]:
a = np.arange(12).reshape(4, 3)
b = np.arange(100, 103)
c = np.arange(1000, 1004)
d = b.reshape(1, 3)

In [0]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [0]:
b

array([100, 101, 102])

In [0]:
a+b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [0]:
c

array([1000, 1001, 1002, 1003])

In [0]:
a+c

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [0]:
a+b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [0]:
a+d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [0]:
b  # 벡터

array([100, 101, 102])

In [0]:
d  # 행렬

array([[100, 101, 102]])