####  axis 이해하기

 - 몇몇 함수에는 axis keyword 파라미터가 존재
 - axis 값이 없는 경우에는 전체 데이터에 대해 적용
 - axis 값이 있는 경우에는 해당 axis를 따라서 연산 적용
 
 - aixs를 파라미터로 갖는 함수를 이용하기
     - 거의 대부분의 연산 함수들이 axis 파라미터를 이용
     - 이 경우, 해당 값이 주어졌을 때, 해당 axis를 따라서 연산이 적용
         - 따라서 결과는 해당 axis가 제외된 나머지 차원의 데이터만 남게 됨
     - ex) np.sum, np.mean. np.any 등

In [0]:
x = np.arange(16).reshape(4, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [0]:
np.sum(x, axis=1)

array([ 6, 22, 38, 54])

In [0]:
np.sum(x, axis=0)

array([24, 28, 32, 36])

#### 행렬에 적용하기 

In [0]:
y = np.arange(15).reshape(3, 5)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [0]:
np.mean(y, axis=0)  # 행

array([5., 6., 7., 8., 9.])

In [0]:
np.mean(y, axis=1)  # 열

array([ 2.,  7., 12.])

#### 3차원 텐서에 적용하기 

In [0]:
z = np.arange(36).reshape(3, 4, 3)
z

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [0]:
np.sum(z, axis=1)

array([[ 18,  22,  26],
       [ 66,  70,  74],
       [114, 118, 122]])

In [0]:
np.mean(z, axis=2)

array([[ 1.,  4.,  7., 10.],
       [13., 16., 19., 22.],
       [25., 28., 31., 34.]])

In [0]:
np.sum(z, axis=-1)

array([[  3,  12,  21,  30],
       [ 39,  48,  57,  66],
       [ 75,  84,  93, 102]])

#### axis 값이 tuple인 경우

 - 해당 tuple에 명시된 모든 axis에 대해서 연산

In [0]:
z

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [0]:
np.sum(z, axis=(0, 2))

array([117, 144, 171, 198])

#### Boolean indexing

 - ndarray 인덱싱 시, bool list 를 전달하여 True 인 경우만 필터링
 
 
 - broadcasting 을 활용하여 ndarray로부터 bool list 얻기
     ex) 짝수인 경우만 찾아보기

In [0]:
x = np.random.randint(1, 100, (3, 5))
x

array([[39, 38, 89, 20, 28],
       [22,  1, 74,  2, 37],
       [52, 34, 97, 87, 27]])

In [0]:
even_mask = x % 2 == 0
even_mask

array([[False,  True, False,  True,  True],
       [ True, False,  True,  True, False],
       [ True,  True, False, False, False]])

#### bool list 를 인덱스로 전달

In [0]:
x[even_mask]  # 필 터 적용

array([38, 20, 28, 22, 74,  2, 52, 34])

In [0]:
x[x % 2 == 0]

array([38, 20, 28, 22, 74,  2, 52, 34])

In [0]:
x[x > 30]

array([39, 38, 89, 74, 37, 52, 34, 97, 87])